services:

  db:
    container_name: db_casatudor
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_DATABASE: ${DB_DATABASE:-casatudor}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network_casatudor
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    container_name: frontend_casatudor
    build: 
      dockerfile: Dockerfile
      context: ./nuxt
    environment:
      - NUXT_PORT=9094
      - HOST=0.0.0.0
    volumes:
      - ./nuxt:/usr/src/nuxt-app
      - ./nuxt/package.json:/usr/src/nuxt-app/package.json
      - /usr/src/nuxt-app/node_modules
    ports:
      - "9094:9094"
      - "24678:24678"
    networks:
      - network_casatudor

  backend:
    container_name: backend_casatudor
    build: 
      dockerfile: Dockerfile
      context: ./strapi
    env_file: ./strapi/.env
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/emails:/opt/app/emails
      - ./strapi/package.json:/opt/package.json
      - ./strapi/yarn.lock:/opt/yarn.lock
      - ./strapi/.env:/opt/app/.env
      - ./strapi/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - network_casatudor

volumes:
  db_data:

networks:
  network_casatudor: {}