services:
  frontend:
    container_name: frontend_containter
    restart: always
    networks:
      - front-tier
    volumes:
      - ./:/usr/src/nuxt-app/dist

    # Nginx
  casatudor_nginx:
    image: nginx:alpine
    container_name: casatudor_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/usr/src/nuxt-app/dist
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend
    networks:
      network_casatudor:
        aliases:
          - casatudor.localhost

  backend:
    container_name: strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi

networks:
  network_casatudor:
    name: network_casatudor
    external: true
  strapi: {}